### ISSUE TITLE
v10 roadmap

### ISSUE THREAD

**Issue by kanadgupta** [readmeio/rdme#1109]
## `v10`
- [ ] `openapi` replacement (internal: RM-11384)
- [ ] https://github.com/readmeio/rdme/pull/1107
- [ ] https://github.com/readmeio/rdme/pull/1104
- [ ] https://github.com/readmeio/rdme/pull/1082
- [ ] https://github.com/readmeio/rdme/pull/1108

## non-breaking
- [ ] [Volta](https://volta.sh/) guidance?
- [ ] Remove `lastUpdatedHash` insertion ([internal ticket](https://linear.app/readme-io/issue/RM-8207))
- [ ] https://github.com/readmeio/rdme/issues/645

## other eventual breaking changes?
- [ ] Remove `workingDirectory` argument from `openapi` family of commands (RM-7754, #904)
- [ ] Remove logic for triple tagging (i.e. `v9`, `v9.0.0`, ~~`9.0.0`~~)

**Comment by kanadgupta** [comment]
closing in favor of https://github.com/readmeio/rdme/pull/1113
